version: "2"

exclude_patterns:
  - "packages/app/src/gql/*"
  - "packages/scrapy/src/gql/*"
  - "packages/nest/src/_autogen/*"
  - "**/*.config.js"
  - "**/*.config.cjs"
  - "**/*.config.ts"
  - "**/.eslintrc.js"
  - "packages/nest/src/**/*.spec.ts" # temporarily disable checks for tests

checks:
  method-lines:
    config:
      threshold: 50
  similar-code:
    config:
      threshold: 95
