version: "2"

exclude_patterns:
  - "packages/app/src/gql/*"
  - "packages/scrapy/src/gql/*"
  - "packages/nest/src/_autogen/*"
  - "*.config.js"
  - "*.config.cjs"
  - "*.config.ts"
  - "*rc.js"
  - "*.spec.ts" # temporarily disable checks for tests