services:
  database:
    image: postgres:12
    restart: always
    environment:
      POSTGRES_PASSWORD: kittycatcat
      POSTGRES_USER: cat
      POSTGRES_DB: caats
  caats:
    image: kpostekk/caats
    restart: always
    env_file:
      - .env
    environment:
      DATABASE_URL: postgres://cat:kittycatcat@database/caats
      SECRET_KEY: supersecretkey
    ports:
      - 3000:3000
    depends_on:
      - database