services:
  database:
    image: postgres:12
    restart: always
    environment:
      POSTGRES_PASSWORD: kittycatcat
      POSTGRES_USER: cat
      POSTGRES_DB: caats
      TZ: Europe/Warsaw
  app:
    image: ghcr.io/kpostekk/caats:latest-app
    build:
      target: app
      dockerfile: Dockerfile
      context: .
      args:
        GOOGLE_CLIENT_ID: ${GOOGLE_CLIENT_ID}
    restart: always
    environment:
      TZ: Europe/Warsaw
      NEST_ADDR: http://nest:3000
      CADDY_ADDR: "*:80"
    depends_on:
      - database
    ports:
      - 80:80
  nest:
    image: ghcr.io/kpostekk/caats:latest
    build:
      target: nest
      dockerfile: Dockerfile
      context: .
    restart: always
    env_file:
      - .env
    environment:
      DATABASE_URL: postgres://cat:kittycatcat@database/caats
      TZ: Europe/Warsaw
    depends_on:
      - database
  nest-migrate:
    image: ghcr.io/kpostekk/caats:latest
    command: "pnpm prisma migrate deploy"
    environment:
      DATABASE_URL: postgres://cat:kittycatcat@database/caats
    depends_on:
      - database
  scrapy:
    build:
      target: scraper
      dockerfile: Dockerfile
      context: .
    restart: always
    depends_on:
      - app
    command: node dist/index.js --api http://app:3000/graphql
    environment:
      TZ: Europe/Warsaw