services:
  database:
    image: postgres:12
    restart: always
    environment:
      POSTGRES_PASSWORD: kittycatcat
      POSTGRES_USER: cat
      POSTGRES_DB: caats
      TZ: Europe/Warsaw
  app:
    image: ghcr.io/kpostekk/caats:latest
    build:
      target: application
      dockerfile: Dockerfile
      context: .
    restart: always
    env_file:
      - .env
    environment:
      DATABASE_URL: postgres://cat:kittycatcat@database/caats
      TZ: Europe/Warsaw
    ports:
      - 3000:3000
    depends_on:
      - database
  scrapy:
    build:
      target: scraper
      dockerfile: Dockerfile
      context: .
    restart: always
    depends_on:
      - app
    command: node dist/index.js --api http://app:3000/graphql
    environment:
      TZ: Europe/Warsaw