name: Run jest with coverage

on:
  push:
    paths:
      - "src/"
      - "test/"
      - "package.json"
      - "yarn.lock"
      - ".github/workflows/*.yml"

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 19.x
      - run: yarn --frozen-lockfile
      - run: yarn test --coverage
